apiVersion: v1
kind: Namespace
metadata:
  name: supermercado

---
apiVersion: v1
kind: Service
metadata:
  name: sqlserver
  namespace: supermercado
spec:
  ports:
  - port: 1433
    targetPort: 1433
  selector:
    app: sqlserver

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sqlserver
  namespace: supermercado
spec:
  serviceName: sqlserver
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sqlserver-secrets
              key: sa-password
        volumeMounts:
        - name: sqlserver-storage
          mountPath: /var/opt/mssql
        resources:
          requests:
            cpu: 500m
            memory: 2Gi
          limits:
            cpu: 1000m
            memory: 4Gi
  volumeClaimTemplates:
  - metadata:
      name: sqlserver-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi

---
apiVersion: v1
kind: Secret
metadata:
  name: sqlserver-secrets
  namespace: supermercado
type: Opaque
stringData:
  sa-password: "YourSecurePassword123!@"
