Write-Host "=== Demo Hector Jesus - Supermercado Online ===" -ForegroundColor Green
Write-Host "1) Abre una terminal y ejecuta la API:"
Write-Host "   dotnet run --project supermercado.API/supermercado.API.csproj"
Write-Host ""
Write-Host "2) En otra terminal ejecuta el simulador:"
Write-Host "   dotnet run --project Supermercado.SimuladorCompras/Supermercado.SimuladorCompras.csproj"
Write-Host ""
Write-Host "3) Ejecuta pruebas xUnit:"
Write-Host "   dotnet test supermercado.API.Tests/supermercado.API.Tests.csproj"
Write-Host ""
Write-Host "4) Ejecuta K6:"
Write-Host "   k6 run tests/load/k6-supermercado-hector.js"
Write-Host ""
Write-Host "5) Swagger: http://localhost:5143/swagger"
